### ISSUE TITLE
`addRange` doesn't scale values to range

### ISSUE THREAD

**Issue by bensaufley** [quarterto-archive/Elessar#89]
Creating a new range with `.addRange()` doesn't process them to scale, instead just passing the raw values through.

For example:

``` javascript
var range = new RangeBar( min: 0, max: 100 );
…
range.addRange([0, 15]);
```

Creates a new range that is 1500% wide, rather than 15% wide. It looks like `valueParse` might be used for that, but creating a `valueParse` function like below has no effect:

``` javascript
valueParse: function (val) {
  return (val - this.min)/(this.max - this.min)
}
```

**Comment by quarterto** [comment]
`addRange` takes range values (0 to 1) instead of bar values (`min` to `max`). You can pass the values through `abnormalise` first, [like `setVal` does](https://github.com/quarterto/Elessar/blob/develop/lib/rangebar.js#L159). I'm keen to keep backwards compatibility, so I won't change `addRange` to do this yet.
